author: "Adorkable"
author_url: "https://adorkable.io"
github_url: "https://github.com/Adorkable/swift-log-format-and-pipe"
github_file_prefix: "https://github.com/Adorkable/swift-log-format-and-pipe/tree/0.1.2"
readme: "README.md"
copyright: "CC 2019 Adorkable"
theme: fullwidth
module: LoggingFormatAndPipe
use_safe_filenames: true
